# [問題]
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#                         1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
# フィボナッチ数列は1,2から始まり、前の項との足し算が次の項になっている。
# 10項目までの例: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# フィボナッチ数列の項で、400万を超えない値の偶数の和はいくつになりますか？

result = 0

# NOTE: メモ化してこ。
def fib(n)
  @mem = []
  @mem[n] ||= (n < 2) ? n : fib(n -1) + fib(n -2)
end

# NOTE: 無限ループは ruby 2.6 から (1..) で書ける
loop.with_index do |_, i|
  cal = fib(i)
  break if cal  > 4_000_000
  result += cal if cal % 2 == 0
end

puts result
